"""Core interface schemas for the VEH Scientist system.

All module boundaries exchange these typed contracts.
"""

from .schemas import (
    BaselineSpec,
    CandidateDesignFamily,
    ClaimCard,
    CorpusDocument,
    CriticDecision,
    DerivationCard,
    DiscoverTaskCard,
    DiscoveryProgramState,
    DiscoveryStep,
    ElectricalParams,
    EnvelopeConstraints,
    EvidenceRecord,
    ExcitationSpec,
    ExperimentArtifact,
    FrequencyTarget,
    GapCandidate,
    GateResult,
    HarvestingSpec,
    HypothesisCard,
    MechanismScreenResult,
    MemoryRecord,
    MetricValue,
    RoundState,
    StructuralParams,
    SuppressionSpec,
    TaskCard,
    ToolRunRecord,
    TransducerParams,
    VerificationResult,
)

__all__ = [
    "BaselineSpec",
    "CandidateDesignFamily",
    "ClaimCard",
    "CorpusDocument",
    "CriticDecision",
    "DerivationCard",
    "DiscoverTaskCard",
    "DiscoveryProgramState",
    "DiscoveryStep",
    "ElectricalParams",
    "EnvelopeConstraints",
    "EvidenceRecord",
    "ExcitationSpec",
    "ExperimentArtifact",
    "FrequencyTarget",
    "GapCandidate",
    "GateResult",
    "HarvestingSpec",
    "HypothesisCard",
    "MechanismScreenResult",
    "MemoryRecord",
    "MetricValue",
    "RoundState",
    "StructuralParams",
    "SuppressionSpec",
    "TaskCard",
    "ToolRunRecord",
    "TransducerParams",
    "VerificationResult",
]
